import React from 'react';
import { GroundingSource } from '../types';

interface FooterProps {
    sources: GroundingSource[];
}

export const Footer: React.FC<FooterProps> = ({ sources }) => {
  return (
    <footer className="w-full bg-[#141414] text-gray-500 py-12 px-4 md:px-12 text-sm mt-12 border-t border-gray-800">
        <div className="max-w-6xl mx-auto">
            <div className="flex flex-col md:flex-row justify-between mb-8">
                <div>
                    <h3 className="text-white mb-4 font-semibold">Sources & Data</h3>
                    <p className="mb-2">Data generated by Google Gemini 2.5 Flash.</p>
                    {sources.length > 0 && (
                        <div className="mt-4">
                            <p className="text-xs font-bold text-gray-400 uppercase mb-2">Verified via Google Search</p>
                            <ul className="grid grid-cols-1 md:grid-cols-2 gap-2">
                                {sources.map((source, i) => (
                                    <li key={i}>
                                        <a 
                                            href={source.uri} 
                                            target="_blank" 
                                            rel="noreferrer"
                                            className="hover:underline hover:text-white truncate block max-w-[300px]"
                                        >
                                            {source.title}
                                        </a>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}
                </div>
                <div className="mt-8 md:mt-0 grid grid-cols-2 gap-8">
                    <ul>
                        <li className="mb-2 hover:underline cursor-pointer">Audio Description</li>
                        <li className="mb-2 hover:underline cursor-pointer">Investor Relations</li>
                        <li className="mb-2 hover:underline cursor-pointer">Legal Notices</li>
                    </ul>
                    <ul>
                         <li className="mb-2 hover:underline cursor-pointer">Help Center</li>
                        <li className="mb-2 hover:underline cursor-pointer">Jobs</li>
                        <li className="mb-2 hover:underline cursor-pointer">Cookie Preferences</li>
                    </ul>
                </div>
            </div>
            <div className="text-center md:text-left">
                <button className="border border-gray-500 px-4 py-1 hover:text-white mb-4">Service Code</button>
                <p>&copy; 2024 Netflix Trends Demo</p>
            </div>
        </div>
    </footer>
  );
};
